keys:
  - &admin age1yubikey1qwja8k752hpjtt9w0l847fdpm7m0ury560qnd6alq7t537jvhcznqxww4h8
  # Users per machine
  - &otogaki_tsutsuyami age1lhxarync6hasuzwrs99ef6np8de2a2rfs0qrv7rekv8d57q8e47spcy539
  - &otogaki_utsusemi age143wa96cj9xywqhdm6kv77uqngg0tumdhvfyqh7pz89jsrujpev0slsz43x
  # - &otogaki_shinonome xxxxx
  # - &otogaki_niwatazumi xxxxx
  # - &otogaki_sazanami xxxxx
  # - &otogaki_tamazusa xxxxx
  # - &rkawata_momokagari xxxxx
  # Machines
  - &tsutsuyami age1er88d8zrfatkvtsyrdunppqz2kagy48p6zd8jaqhh260lkfp6peq4wl6kq
  - &utsusemi age1245wq459mrmqvaywx6flatke2m557j8azsvs4kf2alnvxu5063sqzsjj8v
  # - &shinonome xxxxx
  # - &niwatazumi xxxxx
  # - &sazanami xxxxx
  # - &tamazusa xxxxx
  # - &momokagari xxxxx
creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *admin
          - *tsutsuyami
          - *utsusemi
          # - *shinonome
          # - *niwatazumi
          # - *sazanami
          # - *tamazusa
          # - *momokagari
  - path_regex: users/otogaki/secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *admin
          - *otogaki_tsutsuyami
          - *otogaki_utsusemi
          # - *otogaki_shinonome
          # - *otogaki_niwatazumi
          # - *otogaki_sazanami
          # - *otogaki_tamazusa
# - path_regex: users/rkawata/secrets/[^/]+\.yaml$
#   key_groups:
#     - age:
#         - *admin
#         - *rkawata_momokagari
# - path_regex: hosts/tsutsuyami/secrets/[^/]+\.yaml$
#   key_groups:
#     - age:
#         - *admin
#         - *tsutsuyami
# - path_regex: hosts/utsusemi/secrets/[^/]+\.yaml$
#   key_groups:
#     - age:
#         - *admin
#         - *utsusemi
# - path_regex: hosts/shinonome/secrets/[^/]+\.yaml$
#   key_groups:
#     - age:
#         - *admin
#         - *shinonome
# - path_regex: hosts/niwatazumi/secrets/[^/]+\.yaml$
#   key_groups:
#     - age:
#         - *admin
#         - *niwatazumi
# - path_regex: hosts/sazanami/secrets/[^/]+\.yaml$
#   key_groups:
#     - age:
#         - *admin
#         - *sazanami
# - path_regex: hosts/tamazusa/secrets/[^/]+\.yaml$
#   key_groups:
#     - age:
#         - *admin
#         - *tamazusa
# - path_regex: hosts/momokagari/secrets/[^/]+\.yaml$
#   key_groups:
#     - age:
#         - *admin
#         - *momokagari
