keys:
  # - &admin xxxxx
  # Users per machine
  - &otogaki_tsutsuyami age1tdat96efnae3g6x5p5aw70kak804ar7jj94dx72vumn76rvf5qcsq82pp8
  - &otogaki_utsusemi age143wa96cj9xywqhdm6kv77uqngg0tumdhvfyqh7pz89jsrujpev0slsz43x
  # - &otogaki_niwatazumi xxxxx
  # - &otogaki_sazanami xxxxx
  # - &rkawata_momokagari xxxxx
  # Machines
  - &tsutsuyami age13eqkelhxncfe00s9zuwzparcg0xzl44h9an9syvs5wcnztlthpes84tqqj
  - &utsusemi age1245wq459mrmqvaywx6flatke2m557j8azsvs4kf2alnvxu5063sqzsjj8v
  # - &momokagari xxxxx
  # - &niwatazumi xxxxx
  # - &sazanami xxxxx
creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      # - gpg:
      #     - *admin
      - age:
          - *tsutsuyami
          - *utsusemi
          # - *momokagari
          # - *niwatazumi
          # - *sazanami
  - path_regex: users/otogaki/secrets/[^/]+\.yaml$
    key_groups:
      # - gpg:
      #     - *admin
      - age:
          - *otogaki_tsutsuyami
          - *otogaki_utsusemi
          # - *otogaki_niwatazumi
          # - *otogaki_sazanami
# - path_regex: users/rkawata/secrets/[^/]+\.yaml$
#   key_groups:
#     - gpg:
#         - *admin
#     - age:
#         - *rkawata_momokagari
# - path_regex: hosts/tsutsuyami/secrets/[^/]+\.yaml$
#   key_groups:
#     - gpg:
#         - *admin
#     - age:
#         - *tsutsuyami
# - path_regex: hosts/utsusemi/secrets/[^/]+\.yaml$
#   key_groups:
#     - gpg:
#         - *admin
#     - age:
#         - *utsusemi
# - path_regex: hosts/momokagari/secrets/[^/]+\.yaml$
#   key_groups:
#     - gpg:
#         - *admin
#     - age:
#         - *momokagari
# - path_regex: hosts/niwatazumi/secrets/[^/]+\.yaml$
#   key_groups:
#     - gpg:
#         - *admin
#     - age:
#         - *niwatazumi
# - path_regex: hosts/sazanami/secrets/[^/]+\.yaml$
#   key_groups:
#     - gpg:
#         - *admin
#     - age:
#         - *sazanami
