# ================================================
# YAKUMO PROJECT METADATA
# The Single Source of Truth for global constants.
# ================================================

[project]
name = "yakumo"

[network]
base_domain = "yakumo.org" # The primary apex domain for all self-hosted services.
internal_domain = "mesh.yakumo.org" # The local network mesh domain (e.g., Tailscale/Headscale magic DNS).
dns_provider = "cloudflare"

[security]
acme_email = "contact@younagi.dev"

[[users]]
username = "otogaki"
name = "Ohma Togaki"
email = "otogaki@yakumo.org"

[[users]]
username = "rkawata"
name = "Reiji Kawata"
email = "rkawata@yakumo.org"

[[hosts]]
name = "tsutsuyami"
username = "otogaki"
platform = "x86_64-linux"
variant = "nixos"
role = "workstation"

[[hosts]]
name = "shinonome"
username = "otogaki"
platform = "aarch64-linux"
variant = "nixos-apple-silicon"
role = "workstation"

[[hosts]]
name = "utsusemi"
username = "otogaki"
platform = "x86_64-linux"
variant = "nixos-wsl"
role = "workstation"

# [[hosts]]
# name = "momokagari"
# username = "rkawata"
# platform = "aarch64-darwin"
# variant = "nix-darwin"
# role = "workstation"

# [[hosts]]
# name = "niwatazumi"
# username = "otogaki"
# platform = "x86_64-linux"
# variant = "nixos"
# role = "server"
# services = [
#   "rustic",
#   "syncthing",
#   "tailscale"
# ]

# [[hosts]]
# name = "sazanami"
# username = "otogaki"
# platform = "x86_64-linux"
# variant = "nixos"
# role = "server"
# services = [
#   "adguardhome",
#   "caddy",
#   "home-assistant",
#   "kanidm",
#   "mosquitto",
#   "owntracks",
#   "tailscale",
#   "vaultwarden"
# ]

# [[hosts]]
# name = "tamazusa"
# username = "otogaki"
# platform = "x86_64-linux"
# variant = "nixos"
# role = "server"
# services = [
#   "headscale",
#   "ntfy-sh",
#   "stalwart-mail",
#   "tailscale"
# ]

# [[guests]]
# name = "hayase"
# hostname = "niwatazumi"
# services = [
#   "anki-sync-server",
#   "calibre-web",
#   "forgejo",
#   "mealie",
#   "paperless-ngx",
#   "shiori"
# ]

# [[guests]]
# name = "minamo"
# hostname = "niwatazumi"
# services = [
#   "grafana"
# ]

# [[guests]]
# name = "minamoto"
# hostname = "niwatazumi"
# services = [
#   "influxdb",
#   "postgresql"
# ]

# [[guests]]
# name = "wadatsumi"
# hostname = "niwatazumi"
# services = [
#   "garage",
#   "immich",
#   "samba"
# ]
