git_signing_key: ENC[AES256_GCM,data:OWirYWlb5G1kaEpjt1Ca4DLAf62v1fV9d6YgOOhTMoz3hmLV+EDbC+4DjNpCbdV5jOoAlS+j/uugRj5QPCClGeXH1T0KLgRwqH3dMyMtBLHvPu+2H8vOmWc+hznVrxgf+jd/i39TMNWo+jSVkKvlMbnxBmrsvrmzOS1KYuKoz6OSarEhyU5WC0byjXAXXDHeDu3D1NAuxiRUQKwVJ8tNvyzVwg==,iv:s/+T4r/9f8rrtassix5abDJJHaBzx5r1MpWgIYpXwKA=,tag:mjaSfNt/1OKPnx9K4wYP1A==,type:str]
sops:
    age:
        - recipient: age1yubikey1qwja8k752hpjtt9w0l847fdpm7m0ury560qnd6alq7t537jvhcznqxww4h8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IGFMWXlJZyBBMHg1WWVW
            VW9JRWM4Qm9VV1QvaEpyTDhSbkJObW15bGNSTlRkcXhmNTltOQpqK2tjN3ZrNjZk
            ZkRKZDBFNHlraHdKcUFrR0pxUEtqUkVweVgyOTZRcjRFCi0tLSBhTlVrdDNQUm9o
            YlZBbzFGWXhUUzcwUUlldFZlOEx4R2Uxdk1iVXBzSW93CjuwQYybqLPgX4EGm0hY
            37T6HVyiu39uLoBLFXNe+AuMvBjx7UrVeO8WmDeIjPY0T6dhqs++Mun01jHxplv6
            P8U=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1er88d8zrfatkvtsyrdunppqz2kagy48p6zd8jaqhh260lkfp6peq4wl6kq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmRm9JZzM4M0Z6bEpMVmdl
            Y0NKWjBMQ012Y0lWS1ltc3ZOUHVrVmkwRndJCkFVWlN1L2NXMTZ1UjdhYlZ1N1VD
            QWcwQ3o5bDFvcUpqOFM4aUJmUlRkQTQKLS0tIC9VRlFraEd4VVp5NU95TVNxMmZ6
            dFpGQTREcFc3NzMyYnhOQ3YrZEtVd1kKP3f1QXtw5XFO1wQoAYz0iU3q+jXFPJrc
            MBeegOKbaFFO6PZaqWNC7jkU0sxMh0vZSRIEXYzNSkCzhQm1lMaP4g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1245wq459mrmqvaywx6flatke2m557j8azsvs4kf2alnvxu5063sqzsjj8v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiK3hMNU1BNEZoNDY2cEh5
            L09TV2lpVU1rYUJmUmpxL3V5TmpqYmxBVGtNCjNIRm02U2t4S0N2KzZWR0ROMW9z
            QWlnbDA3YnBhNXFMSk9mNXc5dld1bVUKLS0tIHB5NnJPS3JVaG50aDhTeTBRN2F4
            ZlZVQ3JsVDZuQ1B4a1p5WFMzNW9CUWsKpP72Pu8OtkC+gazechba1MGj21Po3060
            eUobhoWIjrE+3ABhQQ+w7TJYlr9D1k1gHlGasDaXwpHhkSP49647Tw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T15:24:07Z"
    mac: ENC[AES256_GCM,data:zqbYoZ2vOEj0D8ikp5DepKfbRXDcGVQbA0sLegv2G/TsHr3O/YXUeDCxTYqGt+XS8cVg7gQFp3TaSthEphp0MmQgAS/uUKRox2f09miN6v+f6GIrjN4e/6uL1IpHzjHSVwzerzsBYLfwQi3zrfRA6UqQQ0TotESJhiFVEBquBVg=,iv:ANYZANtgfCAciEqAgveFv9MiV1dHbwq9zABv7wtTRhM=,tag:S6MZQKSJ5WC2yjJu4TQSuw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
