git_signing_key: ENC[AES256_GCM,data:V0w8nfGxbcw8nugIxrXOzLSQMyWSECpOlqEUKcW3R/MPrxCAv/F2huBMrQQe7vgD/fy7c9jzx09LfLF/TXdF/GPQ4kBBMkho8az3O3Xa8EZxqQ3TVzEvNC2s0Kso4Z0UFs1yXUWUQnkq+REZpXJ5V27JAH5dQhEA258ORSFgkw5/4/b8iaEzbmg8TX+UXLlc/0xKHemcGbLkxyzRv8UHvaN3vtXPIlqqbd1sBMdyAgDywnHtoZnO4tPFK2Kqec28tRx0qEDD2h12DyBJA+6jjqnbruNTocDsudA53QGtEpY5c+c/gQ8wqJ3IM9NBXvvHRBv01im1VxiQDt+yvRrwJ+5dBaAwhxMgZz5n/4s2UU723gJr+yjmBEjLfw/0RTB7aJvPh9xkigrQmSdU0/YoUwfaTqkVRozABXgmRE99gRnSx4japavmpNCtfIVgSTkS60bqLBUi2q3PYkkSKcQv6do+c2sA6lAS4BbwemkbURKjs4cOLaUATdGe66AHIjadhMJR8BG4r1Cib+YAvfuk,iv:TR/0PPAPAu6H0U52bt4ELzNWhkzS6J1miLciA7QWI7A=,tag:6Q011dvfOU0AvsCPCJo1gQ==,type:str]
sops:
  age:
    - recipient: age1tdat96efnae3g6x5p5aw70kak804ar7jj94dx72vumn76rvf5qcsq82pp8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5eWxlalQ5N3FjVXhneUhV
        Slhxa0twc2psNEM0YzFWZHhWc2JzZHozT0IwClc0ZUk3UFhDMXFVR1pTNkRGRWwy
        L08yZExjK05OWlVQc2RPc0ZTSjloWTAKLS0tIGhLSy96bjV4bTdaa3JTYXJmY0hB
        L3RTY2h3Y3FrcHlTb20zUXh1RVlkT00KNvLWqO2yZkcn2sZbOY81IDT5N3hLMsLX
        IXfXaA75puEZ7U5NhafR5mCxScJnq5+5AfL1r++VKTbC7Vs2zLQr/Q==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age13eqkelhxncfe00s9zuwzparcg0xzl44h9an9syvs5wcnztlthpes84tqqj
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTSXZ1WStCM2UxdC9tSDFz
        TnZiM1c2ODZMZWxrakJSVHZRc1hySWFZcDBjCnZPQ041WVAyZm9lN01lUkFrcFg1
        b1NjS2hTOXE3QkM3cWZRVml5L2hRdHcKLS0tIGdDTjZPY2JraDdPclIrNmM1TExL
        V3ZaRlhTdFVER0ZOdmZqeWdzTVp5NTgKdNy8iqUBrvRsqqSZiXZed/o29HtapXvQ
        ZaVvGV1jQIACoT+fqgFI6bpl6tfs8wOdPHoChVW4wIDFDBhz4fUuHA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-21T14:41:25Z"
  mac: ENC[AES256_GCM,data:Ol0HMuUSjsIavcpEsT+DKk7XcL+Be5XSosMnMDFvdTCidgkuWWDDs7CrIyQTt3wyUv2HZ1kxPG3kiNP0RF34cFiL/suKtwEBB8KNHKZnx2tkWxMOBSfOSFjutmLovXKIPId+WBoITl2aig/E7XaQqoJq8DYVfhty9K1pecQ9e1E=,iv:Kn0ZHkKBez70MbT1zinoxNM5489r2+dfDXIuYOGTUGE=,tag:IkyzxHioQ8EAxWWE+ObvXQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.10.2
