git_signing_key: ENC[AES256_GCM,data:VrX8G+mnAuXVN3xzgFLU3s/2axJb43hdl29bJ2XI9TU4ZNpUbQwi5rUC0vmBrrHWO2i0IswjeCE+kWe0qt2+U3nJlTTqlABSmjSxevI0R3+1vSyMgHalxumCiEdjBrQLarl0KlCTrVSLIGWsCpvU4xNYRoSffYtPET6TMTGwMVO0WroHjNBhneo077Tdi4mJkR4VSqoAq/F1SYy/x7wqE7LgIHSJ00Ay91XbEeNV0LgvpXkjGOYOPyED3sObPSHGA3Q8HdZwxFxy8GyORRIQXyiqTtcee/4Q6L8zYZK2d5ObE3oX/RhllMFCfJMSFTYFM0sC/h5WKDN9WAQwIcE8y/xdpfUZsm58QUp1BfXTMYaEVipxNUbJI5THy5DxkF4MRZN3QDxCe0SBlOoeRCjErHNlmWFfS6fZODsp7jNmZtp6TOWHh3CrTXY/fo9N+GjrroqlKsZPCeOuLFfusZPj/FFJ95V3zMIki3XMq0Gs8tM33S48xN63PjHlDpfCz4Zh1tEKDKJq1uYphObxZlkGGmSYPt2xP1YFOKpcEuixijgnLJdoOHsu9OiEOUCNqlXOtqOw7s2X9fr/xrHV5u8xauVWNpxjYptX/QqC3b5CAl0g+DQxLwWfLzNRkadOrHGq2mlgdg==,iv:qT1fzH34SqmSpzX+Fi174oT63Kc2JgcYrJCSn47LZvg=,tag:g/44hIYc3uDTswZOkxgCeg==,type:str]
sops:
    age:
        - recipient: age1yubikey1qwja8k752hpjtt9w0l847fdpm7m0ury560qnd6alq7t537jvhcznqxww4h8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IGFMWXlJZyBBMHg1WWVW
            VW9JRWM4Qm9VV1QvaEpyTDhSbkJObW15bGNSTlRkcXhmNTltOQpqK2tjN3ZrNjZk
            ZkRKZDBFNHlraHdKcUFrR0pxUEtqUkVweVgyOTZRcjRFCi0tLSBhTlVrdDNQUm9o
            YlZBbzFGWXhUUzcwUUlldFZlOEx4R2Uxdk1iVXBzSW93CjuwQYybqLPgX4EGm0hY
            37T6HVyiu39uLoBLFXNe+AuMvBjx7UrVeO8WmDeIjPY0T6dhqs++Mun01jHxplv6
            P8U=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1er88d8zrfatkvtsyrdunppqz2kagy48p6zd8jaqhh260lkfp6peq4wl6kq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmRm9JZzM4M0Z6bEpMVmdl
            Y0NKWjBMQ012Y0lWS1ltc3ZOUHVrVmkwRndJCkFVWlN1L2NXMTZ1UjdhYlZ1N1VD
            QWcwQ3o5bDFvcUpqOFM4aUJmUlRkQTQKLS0tIC9VRlFraEd4VVp5NU95TVNxMmZ6
            dFpGQTREcFc3NzMyYnhOQ3YrZEtVd1kKP3f1QXtw5XFO1wQoAYz0iU3q+jXFPJrc
            MBeegOKbaFFO6PZaqWNC7jkU0sxMh0vZSRIEXYzNSkCzhQm1lMaP4g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1245wq459mrmqvaywx6flatke2m557j8azsvs4kf2alnvxu5063sqzsjj8v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiK3hMNU1BNEZoNDY2cEh5
            L09TV2lpVU1rYUJmUmpxL3V5TmpqYmxBVGtNCjNIRm02U2t4S0N2KzZWR0ROMW9z
            QWlnbDA3YnBhNXFMSk9mNXc5dld1bVUKLS0tIHB5NnJPS3JVaG50aDhTeTBRN2F4
            ZlZVQ3JsVDZuQ1B4a1p5WFMzNW9CUWsKpP72Pu8OtkC+gazechba1MGj21Po3060
            eUobhoWIjrE+3ABhQQ+w7TJYlr9D1k1gHlGasDaXwpHhkSP49647Tw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T15:23:44Z"
    mac: ENC[AES256_GCM,data:Ooj0/WsoqJ2gEBXP646/q8Sp5Tcrsi6kKZCsSMCFhz4ndbrIVM6C2lP/SM678B1FztueguT1mqGguMUbJemodewOCHAPFSSksgnlU8bDsEircCCf8dFgH49VO8zHVjYWW1KNDMeeyzgq3CGF/nVS/TZ+NWh/hzjmPOY+xke/NDM=,iv:Zw/gwLtfBLj+4xT+8psnrjxBIJg7Qcb6ysRnvy74Naw=,tag:sBSSyYM9MxACsmWvjRRJ1A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
