git_signing_key: ENC[AES256_GCM,data:VrX8G+mnAuXVN3xzgFLU3s/2axJb43hdl29bJ2XI9TU4ZNpUbQwi5rUC0vmBrrHWO2i0IswjeCE+kWe0qt2+U3nJlTTqlABSmjSxevI0R3+1vSyMgHalxumCiEdjBrQLarl0KlCTrVSLIGWsCpvU4xNYRoSffYtPET6TMTGwMVO0WroHjNBhneo077Tdi4mJkR4VSqoAq/F1SYy/x7wqE7LgIHSJ00Ay91XbEeNV0LgvpXkjGOYOPyED3sObPSHGA3Q8HdZwxFxy8GyORRIQXyiqTtcee/4Q6L8zYZK2d5ObE3oX/RhllMFCfJMSFTYFM0sC/h5WKDN9WAQwIcE8y/xdpfUZsm58QUp1BfXTMYaEVipxNUbJI5THy5DxkF4MRZN3QDxCe0SBlOoeRCjErHNlmWFfS6fZODsp7jNmZtp6TOWHh3CrTXY/fo9N+GjrroqlKsZPCeOuLFfusZPj/FFJ95V3zMIki3XMq0Gs8tM33S48xN63PjHlDpfCz4Zh1tEKDKJq1uYphObxZlkGGmSYPt2xP1YFOKpcEuixijgnLJdoOHsu9OiEOUCNqlXOtqOw7s2X9fr/xrHV5u8xauVWNpxjYptX/QqC3b5CAl0g+DQxLwWfLzNRkadOrHGq2mlgdg==,iv:qT1fzH34SqmSpzX+Fi174oT63Kc2JgcYrJCSn47LZvg=,tag:g/44hIYc3uDTswZOkxgCeg==,type:str]
sops:
    age:
        - recipient: age1yubikey1qwja8k752hpjtt9w0l847fdpm7m0ury560qnd6alq7t537jvhcznqxww4h8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IGFMWXlJZyBBNVkxQ3NC
            NVlMSS82d3hzUjhwYTRxRHZoTHV6RGRuaDBpODcvdzhQMmVMRQpsZHlzWUh2Q1Nj
            Sm84Q1JVaWJCMnJaR0VvM0dZQ1NGMHhsRUJmME5pd1pjCi0tLSBPSTFaRGRRRlNL
            MDZYSFRUdDhEZjRpak8zbXo3Mi9rQ1Q2Y2Z0WVZRdVlJCgzoGeDTjsm+iTHBvSoo
            Z+5udL7Xq6Vz71lXOSexORkg86pVfrIhpD9nVCs1nFr+eq/mXK9JrPo7bKSQkjgN
            rp8=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1er88d8zrfatkvtsyrdunppqz2kagy48p6zd8jaqhh260lkfp6peq4wl6kq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYVnlQT20zK3dTNWlQNmg2
            dW1mSTMzRUR0d0lzbXJqVW9iVitndlBQUEdVCjBmTVhQMlNsT1lrUzdXa3hZY2cx
            YkgwOG1qNEduc2JPVExkbWFScDBmVmsKLS0tIGpTTm5tQnJRZ0NORi9YM01JRU00
            VG80dFl6d1VzQVFYSTBNa0p4R3FMbGcKQZN1EmmUiQO0RIFRMbpBgKO0DzJrODDL
            fQfwb8djLlnWlQTCfLbAE4s4e+xyKInotjzgWC5NhUv0n3eLkzmi+A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1245wq459mrmqvaywx6flatke2m557j8azsvs4kf2alnvxu5063sqzsjj8v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvY0FpWUJSR29wOWhzUzlD
            L29rWWtrVGI5OXQ0VWRBMWg3UXpNWTBCeEU4Cll2VjlTYUxTajI2OW1Ma3J3YitY
            QmUvcEFNVitXNlFFVjJoUmVVZXhwWlUKLS0tIHgzWGJ2N09IZXdTOGtRVTRRWTU5
            YXhKSGQrZVVIeitsVGh3dm1zZStDZG8KRCB4i7Cl1+c1qcQsLnRAEj59G4N3/6xC
            rhlE+LPVQyAKfwfvH2s7FEizWUS9vJkEYDUvM/PEex/2ngxB5sVbkw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ms65f94a5e56zugqxwjlmgx9k8f5at5cmexywznv0gtwrn44sutqvlxscx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4ZXdETStOZnpnMXJldWhZ
            WUN6UUpxckFKQ2RnRG1mcjJLNTRFVkhJdVZjCitlaTkwMlI2RGtVV2lMMEdadVAy
            UGJ2QkRYTCszOHY4bGQ3Vll6WkNBUFEKLS0tIHJ1K2U0YWZ3M2RFTFU0eWJ4dUFH
            SEV0MVh6TGhwWGF1K3ZnYXNzV0JDM3cKvhKZWOjb5ugeblytiugJq8Cbzl5VaLbK
            PdD/Q0KzSM1Qp/01Bxa4tn/NCDyNQ2QQUoXHp7eSPA52MxLJkyzulA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T15:23:44Z"
    mac: ENC[AES256_GCM,data:Ooj0/WsoqJ2gEBXP646/q8Sp5Tcrsi6kKZCsSMCFhz4ndbrIVM6C2lP/SM678B1FztueguT1mqGguMUbJemodewOCHAPFSSksgnlU8bDsEircCCf8dFgH49VO8zHVjYWW1KNDMeeyzgq3CGF/nVS/TZ+NWh/hzjmPOY+xke/NDM=,iv:Zw/gwLtfBLj+4xT+8psnrjxBIJg7Qcb6ysRnvy74Naw=,tag:sBSSyYM9MxACsmWvjRRJ1A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
