# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  yaegaki = {
    pname = "yaegaki";
    version = "172210972c899784220635aeb036e5145851a615";
    src = fetchFromGitHub {
      owner = "brklntmhwk";
      repo = "yaegaki";
      rev = "172210972c899784220635aeb036e5145851a615";
      fetchSubmodules = false;
      sha256 = "sha256-UIXisiERqV9atWdMD6mEPrijg6cvFHaexa+9xfH0Ss0=";
    };
    date = "2026-01-13";
  };
}
