git_signing_key: ENC[AES256_GCM,data:0QB5Cj7Xq/L2hEnW6xmMmGRHGTJg3XsoZhgEKZ3hzdVKq5OTiOD2GKjGtjbUZ3efYIjV/ofw3QT+TSYwsoiYeD9qsg9NcQspWhz3uGgnAz8fSUP01iFAqn7rptI8vyt2fL3lKPbIOqQFuRquZpCdjn5GcywnuIl3qNhg/7UvXcv9jz/rhIQZJ+2ORSnSolkTDXaasAO+6UyvyBs/macxnscnu2hxzdqXYH0jxFl2Ez7WkWigsRcmXKaR94QXYp+9NsADh8cTWfBt8c9+gjwx618Opw+FuSzMNUKsNsyzoBY318tJisy5sAgtdev5IYCUl55uRI7y/476TXzwyOogdP6XvaCqZpOwLsYfW23jh6VfQh1AHCE/MjOenmBLKnfS1Q9u7oVPPvSE8UAokCpayTw10+LTsCH7G6CZgZfcmuGxGXi/7Nqc9jnKUnC5xjL5a9Q0gQZVKo2LB7AgiE7V4IftdeOTEMPvDv5yj6Sug5+05GxjTmUc9yMc8a6gWuf4fZr22J7UjiL91zcOaYTq,iv:aRjiOCzW88IPH1sU5Kil4HDjtvAeIjoTei7QQzzl6h4=,tag:QX5GETUnS8LyXaxFh6GEUA==,type:str]
sops:
  age:
    - recipient: age1tdat96efnae3g6x5p5aw70kak804ar7jj94dx72vumn76rvf5qcsq82pp8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSNFB4cE56Vk00QmRhaUZx
        NTNqOGd4Y1pKRllQUzFKQ2tpYmVIN3Z1N0VvClVxZVJGN09MUWJGWXI5ZFNCQ0lE
        UU0rYkRjNTM3azkvN2ZvRklVaXRuV0kKLS0tIDZVbU1JVzU5K0FuMUZ0eVFBQXV6
        YlVmMzJSR1lIQ29ZSWJqY0xDdGRlM0kKgmxUcLv3zw3J0IUvTSc7BbeIRKKwEIlQ
        CZZAp0YKYBZDE5FAuDFqBwrmAt2WrUH8bm/BWnrz9bn5cXftUwRPqQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age13eqkelhxncfe00s9zuwzparcg0xzl44h9an9syvs5wcnztlthpes84tqqj
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0eVVKa1lrSndPa2NWVHZr
        NGplaHNJSU9DczdxbjRsK1lBNC9PR2hsQm0wClBneUxRQmIyT3o0cElWcHlaMVVw
        QmlBUWtMZThGMTlXTjhxRFdKZG01T0EKLS0tIGtyWHkxU01Gb1ZzRUM3YUJOUEpz
        M1VaRHdHQUxESGZ5aHRBZEhISmZrZjgKJO6N3QGwJi5z66+5kXjx2pfULb/35xzt
        sHqSiB+Hss32L/Z+fp2XcXN3TChFPZCtS44+vuYN2O0Pw97fEUYwoA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-30T01:20:34Z"
  mac: ENC[AES256_GCM,data:hjFXZGbZOUSJl8/8s1qxB0eqb71Vb8bCqKyK+0glxVw3+w8b8gJvyBVoEwnyKni2K8gREd9TLacBVd72Z37hMuK14ocEHF+Rnktlkgv/bu2SfbJchlWj/yAzke+AimFCNIwYeIrKbViaWDI70LQjWddtmZC+aDm6p3W6XSwu/oQ=,iv:5MeEtwtcd2/rctoIRRsJ+XEZpWqQ9t47STxkkBkMgR4=,tag:01RZwLFsi5XaKktYJhvmFA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
