# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools, }: {
  yaegaki = {
    pname = "yaegaki";
    version = "d11c6cef9b359be25cd237fc8b5a0152100165ab";
    src = fetchFromGitHub {
      owner = "brklntmhwk";
      repo = "yaegaki";
      rev = "d11c6cef9b359be25cd237fc8b5a0152100165ab";
      fetchSubmodules = false;
      sha256 = "sha256-i3vraJLh2zhcPQShv/rVxY9s2fuF7yim8pwkUwtIebU=";
    };
    date = "2026-01-26";
  };
}
