gh_token_for_mcp: ENC[AES256_GCM,data:xXM1DzciUZUSOLIMQFblsZXhFd8v/+nndKv2p8gvLS5OXj3BywJ8V0NEsELF68+cMY4UJhBALX3Gs0+ZWkGLNfUEu+15t9zU3oi9/O1pGnYrm54uDl8lQkHVJkhG,iv:DB/06mryPDNM+CSV4V8NBCx6duUaaUlUeNXjdjd/MX8=,tag:bKB+cC6wBqHJyo9d5s052A==,type:str]
login_passwd_otogaki: ENC[AES256_GCM,data:tEHJNx+qgFdEOYfvCYXjK5nH,iv:gm/Jhtl4RhV21cDPgptMPEwWRpPwP/IcjUAxqoM2+XY=,tag:9HGPA9uKEm68JYuMBknZeg==,type:str]
login_passwd_rkawata: ENC[AES256_GCM,data:VD9vT6HI803JN7+Di/cGD7oLoK0=,iv:FeY04xpf+if4ag78Qah7r/L2DqCFJxkqvRHv4bHJp8k=,tag:5GF5lG4hJ9krbgeuqY2VWQ==,type:str]
sops:
    age:
        - recipient: age1yubikey1qwja8k752hpjtt9w0l847fdpm7m0ury560qnd6alq7t537jvhcznqxww4h8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IGFMWXlJZyBBNXIzVDRQ
            VUVaUldLdmh1Q2t2OEh4NnlIdWVhenRZNzZRamZ4ekN6cGo3RQpxVWRmd0tLeTd3
            MFNKeCtjbGttanpLclNEblRiazA3UysxaWdoZkZBLytBCi0tLSB2Nzg5V0x1VmNj
            Q2NFa0FhaFJ3L1pQa2lzZ2Q3a1JwRks5c2dGZVludjZBCnEO3BbxwSKnQYH0WIhV
            4Dd2jdjb+N6vbQ2ifUBJz1Ue6lh52OcIqV4XHgoXjrxC0XNisHFMOlNinlAhWRY9
            gBg=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1er88d8zrfatkvtsyrdunppqz2kagy48p6zd8jaqhh260lkfp6peq4wl6kq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGcjhiS0luaHZPeTJkVS9C
            b0hVSjkxWkNqVXZsVDZUVkFaYks5aUw4dWtRCmtoc1V0b1g0T2FjLzB6a0IwUVYx
            VStBSVQzdnlBZHBKRVVZQkRkRXRpbDQKLS0tIEJHYWdBbVpLeGRMMHVrd1luWHlr
            ZlUyUjl3QUd6ZlNkWEd2d2F6R2s4cUEKkNj4BpoHmWFYxPI0cpf32/9ajjRNtDEy
            DhyWhVa2+LEXUMNbuHI5AU6CHWHd1ajDFxcVTJQE/j3+0JXjsuOVXA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1245wq459mrmqvaywx6flatke2m557j8azsvs4kf2alnvxu5063sqzsjj8v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNMnFNb3R4WnY1TzhJQTgr
            UUNWWDZPTUlDcHRLbEhreHJQWlRyelNHTlRJClB2eDRLZTNDMThxc2wwb2FrcHh4
            VUFmUTJJVmZiOGI1akV6Z2tJU01KVUkKLS0tIGdjdEYzaVpFbTdRUkF5bVhacTFE
            emZIZjYyNUxPMm9IZ2gwM2hqL2hzdlkKw7k33kl0/9vyWUAre9e7L87AejB2ReHt
            vPJvAKXvbCJ7wWiZ74EcnGcqZ1XHMxAi0N/oZynGGrcxhFOJtysKWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T14:50:31Z"
    mac: ENC[AES256_GCM,data:3bSMyfNLJ90MpFjt1tvwigCGMEoaisirRNdjkX923OQ7X6N45ZLVWoDwcns5/qbbH1F2aFb2Egc9DT8DtpuXYW1uv2vYDoDcYKRfviijLj1KXI58C0F0XN1YeLofA8oDNy28ClR3FWD5/ossP1wVqqPkV04YeKmtd4XvQR8+7CM=,iv:dS1mRLBCq+kSw/gWcik125Fhc+ugwAj0z5dW/7/rj0k=,tag:ErBHlw9YWcpVxLKIJ2Zx1w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
