gh_token_for_mcp: ENC[AES256_GCM,data:xXM1DzciUZUSOLIMQFblsZXhFd8v/+nndKv2p8gvLS5OXj3BywJ8V0NEsELF68+cMY4UJhBALX3Gs0+ZWkGLNfUEu+15t9zU3oi9/O1pGnYrm54uDl8lQkHVJkhG,iv:DB/06mryPDNM+CSV4V8NBCx6duUaaUlUeNXjdjd/MX8=,tag:bKB+cC6wBqHJyo9d5s052A==,type:str]
login_passwd_otogaki: ENC[AES256_GCM,data:BMb/clPfdrwERfeuknytUYh4s07RArsfoqwrtKU7vYeBQRJiwalG05NfK72Vz3unCQKpsFuMxy4efF0wBvClZZfh04uZzJ/md5iMTbhMFxdZCxnISoB9zv6x20gVRPqbBsBDGrbWRexlcg==,iv:5HezYZRAlaB+8+s7rTOod80PUVstiFvauJpT+q/xZzM=,tag:tIr/PVvLWfuNU0t6tf73Wg==,type:str]
login_passwd_rkawata: ENC[AES256_GCM,data:5aH9P5CyyIo4mjSh+1LSFtFgFmTbSCt82sOF4Cj4yuDBbJUpVNoPKIEWEizwS5+GjC1IPxWAt/xULOsR37XOI04uf1pV2gP90PzuCLHTSGXnf6g8RAj0eIldzSE4SE/9u44xYRdWJzUQ4g==,iv:4Td94xYWEAoL+q/qkUK6d4tlO7YAv42arwb/jVaowF8=,tag:8+7q1ktoFWl/AQ1HTU1YrQ==,type:str]
sops:
    age:
        - recipient: age1yubikey1qwja8k752hpjtt9w0l847fdpm7m0ury560qnd6alq7t537jvhcznqxww4h8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IGFMWXlJZyBBK1BGMWJ6
            N21CQ1o0Q0NVd05pOW4xTVc3QTQwUDJweEhsOE1lRGdGTWxRNQpmVk5qYzJjVHdl
            MmZJaC9VWm1uUXZGWXJITTNJSTIzcDdRN1BJdVU4UzA4Ci0tLSBueDRRbGhmQ2xm
            WVlnQWt4dnhENlVNdzRYdUdNc29vSFhKeXVibGZFU0dJCpfrZ6AEBetk6Yfl6Xvc
            pdM8yveQAeMtJmHxkxSjjrHF+A/3wlhS204V70/nTDFgFqV0NRCIhOIPjkBRxURI
            Yf8=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1er88d8zrfatkvtsyrdunppqz2kagy48p6zd8jaqhh260lkfp6peq4wl6kq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUdWtDRDNrZ1dod2ZEbEdM
            ZnR3YmhFeW9SQjI4U2FiOVJ4UWhjQXZhVFU0ClQvejB3WUNNRHIvVTFDQzBVaGx2
            SWNoMElDNDhqYkg4RmZCTkJ4RFZxQm8KLS0tIDd4TjVmSzBGZDZ4MXNDYWVhYy80
            aHhodHE0UWJpZk1rSlRvQjV1NjNJL00KdnWmD8kunpt5L2SiVF88P/z69LQ4Ar57
            nDf9Vbde7npg8F72CLR92rGbCYJdAmwWHvx2gg900w34nGDTkRv4Pw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1245wq459mrmqvaywx6flatke2m557j8azsvs4kf2alnvxu5063sqzsjj8v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHWmN2M1lTaktWaUxKWUg5
            U0tQZjV2VjRXanFYbUxPVCs0S082TmoxUDNNCk94bE5FN0tOK25DSDRPTys0Y1VL
            Unl0YzBrNDJvdUNtdlRuOUlVY1c1TnMKLS0tIGNETnNlN0IwdG9LdDB1aG5hN2No
            UkRjSEVTUFZCWExXanhCanFiYVZBRmsK/6JUAfrjxOx8xHittlkW7hkX5TBrruny
            AjTFvHuIW01prySlkd3GdZX4xNKOePcmYgQ8XQmJvfvqxu7b+12LXA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ms65f94a5e56zugqxwjlmgx9k8f5at5cmexywznv0gtwrn44sutqvlxscx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvdy9PcUdIYWpDMFZnOUkr
            T0F0elhpNVM5Mzk3dHIzNkFpaXpQbDJMMzBrCno0Y2ljL0lwTTBvMzZUZ294WnBh
            N0x5MVVkSzh3RDhycEd0VWZvaGp1TUkKLS0tIDdxenVSZVJTMWVBZXhtcUlmUXJX
            aFhrNTFEbzRXM3BURWtaVmhaQXZ6ZHMKTGS+FN410zjayctW0S1heaprpGwoo/E3
            Hgrx3MD/7xSyDBn5sQzG4V6t9oQUsSR9da/SSpyR/JKqVyCRC/PSUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T16:38:50Z"
    mac: ENC[AES256_GCM,data:m/iqrsLB/bYFm6P93JL4/sTylchyNI3B7BhJg8kkEGThRIIwQbUnrQ+RN5kha7iMbbWHOCT6yj2jTB2ieaH85IPBTSTUlGP8ss1Mc+RTnvty+LJh6NXwSEUBfvWUnOwZ6uE4rtdvGvc3GEmIqiPTDkqykzQDVxpKZeRGog7pvVs=,iv:lAtZgTguTMz/Nl05iYATqRv+whnGMX9BcfUm3oWgf7A=,tag:DHBuNXEYfmzHcU57juKVYQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
