login_password_otogaki: ENC[AES256_GCM,data:D1+mTWzSlTyTTStPJg==,iv:ebpxkh3AtE1miqA4QC5I9aYuOnPdo10UzEoFqfcOWmk=,tag:T4aAe3HiM2+98dW8mWSJVw==,type:str]
login_password_rkawata: ENC[AES256_GCM,data:bD7qIQb7D5s4KM8V0/y2syFYG9xe,iv:kRTTjzjSsEudcSnbziRbDUJFpk1/rleQ5ijEEEuUt9o=,tag:BD6g2PcqW4L4/JSPSVgChg==,type:str]
gh_token_for_mcp: ENC[AES256_GCM,data:0roB+SZw5x4Sx++fb4Z3D9boHMLrvRx9wxUl1UqqBN5716V0qrBsrsotadV7KSdqo/DIc6C0OnV2iyrWqISdvv5mfzr5T8P0lWTaC76p9mYbeYGOb6QciRCntvBj,iv:Eas11rlrVEWZl64IKFRcY8stqMFPEtR7hjf8s3J3tsk=,tag:AfTzz3M/rYhDiFvF4J3v7A==,type:str]
sops:
  age:
    - recipient: age1tdat96efnae3g6x5p5aw70kak804ar7jj94dx72vumn76rvf5qcsq82pp8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRUVg3VHBLdGhnRlpmZnlP
        SnRjY2RGMS9WdVd2T0NoNGt6VTBSZTd5T1RNCmJUVFNORmlaK2xSWjA1QlI1Wi9Q
        TnNLUXI4d3dTNjhMeXZlUzUxS1BMckEKLS0tIENoQlRHOW9ma0VWV0ZZNEhmc2Ji
        UGRQbjR2dFRBaVFiTURBTXRUMjFZQ2MKCs6CgqBM854wO7HypSfural8u2r1qnLA
        zm3A5YkSrLhUd3IG3Gesf+V+AliCWk7hKzKz0xz7muMzkek/FSl3LA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age13eqkelhxncfe00s9zuwzparcg0xzl44h9an9syvs5wcnztlthpes84tqqj
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOdHUzYWVXWnA5RVQyZ0hs
        Z0FWUitCUXV2dUorMER6R2pVU0tIKzBVSjNJClJrOTFKSzN2Y29Gak1UaEVydGdF
        Ync2NUtoRWpyalpRTVdkTzBXZDM0MkkKLS0tIDY5Slp1N1EzdlZrV2NKQlg4Tksr
        TXl1N3RueXpHUUZqQmh5bXIzaWdhczAKxOujf86z7P6F+V0EndJJu6lQ9D3Vv/2l
        8LLTs/hea9sAAw4E0gP4tH/iymkHBZadw7rTuIbvyzjL82JkQ/wuaA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-21T15:04:52Z"
  mac: ENC[AES256_GCM,data:7BtWIeTdmtf7aeX0c7l4TheA4tllEW4bzaw/DDhfZQTc77UIAPTaN2wFsDvlJWNI3FrCzp/jnUPG8cGgGxqADVU2aguOs+QefDOFFyg9ntcvDWLZi4aq/yQn6/cSmeu12zmh+AXbAVZuX/6fBK2ojZm/hiZDNqcibo7f1Cjsvlk=,iv:Yl7jLH34v6MJ8A28nQkBb+TQJgD7cXBVpNGT1SJQ0Wo=,tag:EzTzM93EfiI7efgLZ/zhlQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.10.2
